### PR TITLE
Dataset Food price of Srilanka

### PR DESCRIPTION
**Pull request by iamrahul8**
This dataset contains Food Prices data for Srilanka.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Merge it under `hacktoberfest`

### CODE REVIEW

**Comment by nikhil25803** [comment]
Hey @iamrahul8, you made separate PR for different datasets at once. Doesn't it look spammy? Please make another PR, adding all the datasets.

**Comment by iamrahul8** [comment]
> Hey @iamrahul8, you made separate PR for different datasets at once. Doesn't it look spammy? Please make another PR, adding all the datasets.

@nikhil25803 , I don't think so. These all datasets have no relation among them. These all are of different field. Just because i have opened these all at same time not make it spammy. If i need then i can open one after one also.
Please have a look , i have opened these all with separate branches. 
waiting for you reply

**Comment by nikhil25803** [comment]
@iamrahul8 | If you do want to add multiple Dataset at a time,. You need to add them in a single PR not seperately.

**Comment by iamrahul8** [comment]
> @iamrahul8 | If you do want to add multiple Dataset at a time,. You need to add them in a single PR not seperately.

Well i need to wait for merge of my previous PR for opening another one ; correct me if i am wrong ?

**Comment by nikhil25803** [comment]
Yes @iamrahul8

**Pull request closed without merging**
