### PR TITLE
Added a dynamic search bar

### PR DESCRIPTION
**Pull request by durgeshm01722**
## Description
I have added a dynamic search bar to search for any databases in the web app of Datasets repo.

# Checklist:
- [X] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [X] I have cross-checked that the dataset I'm uploading is not present in the project
- [X] I have cross-checked that the dataset is present in the correct folder 

## Screenshots 👇

Screenshot 2022-10-16 211251

### CODE REVIEW

**Comment by nikhil25803** [comment]
Hey @durgeshm01722, there are some merge conflicts, please resolve them first.

**Comment by durgeshm01722** [comment]
Okay

**Comment by durgeshm01722** [comment]
@nikhil25803 , I have resolved the merge conflicts. Sorry for that. I didn't realised.

**Comment by nikhil25803** [comment]
No prob @durgeshm01722 , Great work  :)

**Comment by durgeshm01722** [comment]
Thanks 🙌

**Comment by nikhil25803** [comment]
Hey @durgeshm01722 , fix this one please.
image

**Comment by nikhil25803** [comment]
I guess it has been fixed @durgeshm01722 :) 
Leave it for now

**Comment by durgeshm01722** [comment]
It's okay on my side 😯

Screenshot 2022-10-17 014221

**Comment by nikhil25803** [comment]
Looks good this side too :)

**Pull request merged**
